Repository pahud/cdk-spot-one, pull requests merged in 2021-02, with the labels that each got.

#184 chore: upgrade projen and yarn
  .eslintrc.json
  .github/workflows/build.yml
  .github/workflows/projenyarnupgrade.yml
  .github/workflows/rebuild-bot.yml
  .github/workflows/release.yml
  .gitignore
  .npmignore
  .projen/deps.json
  package.json
  tsconfig.eslint.json
  yarn.lock
Labels: auto-merge

#185 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#186 chore: upgrade projen and yarn
  .github/workflows/release.yml
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-merge, projen/upgrade

#187 feat: support instanceInterruptionBehavior property
  src/spot.ts
Labels: auto-merge

#188 fix: instanceInterruptionBehavior not honored in SpotFleet
  .github/workflows/auto-approve-yarn-upgrade.yml
  .projen/deps.json
  .projenrc.js
  API.md
  package.json
  src/spot.ts
  test/__snapshots__/integ.default.test.ts.snap
  yarn.lock
Labels: auto-merge

#191 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#192 chore: upgrade projen and yarn
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-merge, projen/upgrade

#194 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#195 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#196 chore: upgrade projen and yarn
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-merge, projen/upgrade

#197 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#198 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#199 feat: support SpotInstance
  API.md
  README.md
  src/integ.default.ts
  src/spot.ts
  test/__snapshots__/integ.default.test.ts.snap
  test/main.test.ts
  test/spotfleet.test.ts
  test/spotinstance.test.ts
Labels: auto-merge

#200 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#201 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#202 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#203 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#204 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge, projen/upgrade

#205 chore: upgrade projen and yarn
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-merge, projen/upgrade

#207 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge

#208 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge

#209 chore: upgrade projen and yarn
  .github/workflows/rebuild-bot.yml
  .github/workflows/release.yml
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-merge

#210 chore: upgrade projen and yarn
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-merge

#211 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-merge

#212 chore: upgrade projen and yarn
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-merge

#213 chore: upgrade projen and yarn
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-merge

#215 chore: remove InstanceInterruptionBehavior from the testing
  src/integ.default.ts
  test/__snapshots__/integ.default.test.ts.snap
  test/spotinstance.test.ts
Labels: auto-merge

#216 chore: upgrade projen and yarn
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve, auto-merge

#217 chore: upgrade projen and yarn
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve, auto-merge

#218 chore: upgrade projen and yarn
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve, auto-merge

#219 chore: upgrade projen and yarn
  yarn.lock
Labels: auto-approve, auto-merge
